### ISSUE TITLE
현재 개발이 필요한 항목들입니다

### ISSUE THREAD

**Issue by ise-e** [eungyu04/Invaders-SDP#23]
1. 총알갯수 증가에 대한 개발이 현재 enermy 팀의 개발과 충돌이 발생한 상황입니다.
   일단 저희가 Ship 파일에 작성했던 코드는 주석처리하였으니. 픽스 부탁드립니다.

2. 현재 일회성 아이템의 경우 클래스 생성까진 완료되었으나, 적용은 안되어있는 상태입니다.
    이것도 개발 부탁드립니다.

    itempool 클래스가 저희가 만든 파일과 enermy 팀이 만든 파일, 2개가 존재합니다. 
    하나로 통합해주시면 감사하겠습니다.

    체력 증가 코드 또한 Ship 클래스에 존재합니다. 이것또한 하나로 통합하여주시거나, 
    Ship 파일에 존재하는 increaseHealth 클래스를 사용하여 적용시켜주시면 감사하겠습니다.

3. 영구적 아이템은 메인메뉴팀에서 업그레이드 ui와 트리거를 개발해주시기 전까진 적용이 불가합니다.
    빠른 개발은 원하신다면 직접 이부분을 개발하셔도 좋습니다. (저희 팀이 개발하는게 나을것 같다면 코멘트 남겨주세요.)

4. 언제든지 추가적인 아이템이나 아이디어가 있다면 코멘트 남겨주세요

**Comment by eungyu04** [comment]
확인하였습니다

**Comment by eungyu04** [comment]
1. enemy팀에서 모든 총알을 PercingBullet으로 제작하였는데, 그렇다면 기존 한 캐릭터만 죽일 수 있는 Bullet은 아예 사용을 안하는 것으로 방향성을 잡고 개발을 하셨는지 궁금합니다. 만약 그게 아니라면 모든 총알의 기본 세팅은 다시 Bullet으로 돌려놓고 특정 트리거가 작동되었을 때부터의 총알을 PercingBullet으로 바꾸도록 수정하겠습니다.(사실 처음부터 관통 총알을 사용하는 것보다는 이렇게 하는 부분이 더 낫다고 생각하긴 합니다)

2. 구현하였습니다

**Comment by ise-e** [comment]
관통 총알 파일중에 관통 가능한 엔티티 수를 조정할 수 있는 부분이 있습니다.
때문에 enermy 팀에서 작성한 그대로 가되, 
그 수치를 조정하여 사용하면 기존 Bullet 기능도 사용 가능한 확장된 기능으로 사용 가능할 것으로 보입니다.
