### ISSUE TITLE
현재 개발이 필요한 항목들입니다

### ISSUE THREAD

**Issue by ise-e** [eungyu04/Invaders-SDP#65]
-- 1. 아이템 획득시 이후 보라색 적을 처치해도 아이템이 떨어지지 않는 버그가 존재합니다. -- (완료)

2. 다른팀에서 적함선의 배열을 2개로 만들어 개발하여서 폭탄이 제대로 적용되지 않는 버그가 있습니다. (완료)
   현재 이 부분은 다른 팀에서 배열을 하나 삭제해주셔서 버그 발생 여부만 확인해주시면 감사하겠습니다
  
4. 현재 메인메뉴에 업그레이드 트리거가 개발되어서 클래스 호출 코드를 작성 중입니다. (완료)

5. 쉴드 아이템 획득시 피격을 막아주는 기능이 작동하지 않고 있습니다. 픽스 부탁드립니다. (완료)

픽스하거나 개발하실 때 진행할 번호를 코멘트로 적어주시면 감사하겠습니다

**Comment by eungyu04** [comment]
확인했습니다

**Comment by KIM-JEONGMIN0630** [comment]
4하겠습니다.
