### ISSUE TITLE
현재 개발하면 좋을 부분입니다 (필수 x)

### ISSUE THREAD

**Issue by ise-e** [eungyu04/Invaders-SDP#75]
1. 폭탄의 스플레시 데미지를 통해 파괴된 자주색 적 함선이 아이템을 떨어뜨리지 않습니다. (if문을 사용하여 자주색 적일 시, 
    (dropitem 클래스를 호출하면 해결 가능해보입니다. 물론 더 좋은 방법이 있다면 그 방법을 사용하시면 좋습니다.) (완료)

2. 폭탄의 스플레시 적용 로직을 for문을 이용하여, 범위 내의 적을 모두 죽이는 로직을 변경하면 좋을 것 같습니다. (완료)

3. 아이템 획득 시 자주색 적을 죽여도 아이템이 드랍되지 않는 버그를 해결하기 위해 지운 코드로 인해 아이템이 쌓여 오류를 발생시키는 것 같습니다. (이 부분은 enemy 팀에서 해결 중이긴 하지만 원하시는 분은 찾아보셔도 좋을 것 같습니다.) 

4. 현재 피버타임이 적용되지 않고 있습니다. 픽스 부탁드립니다 (완료)

5. 함선의 속도 업그레이드 상승량을 0.5로 조정할 계획입니다. double로 변수 타입 변환이 필요합니다.  (완료)

**Comment by eungyu04** [comment]
1, 2, 5 개발 완료된건가요?

**Comment by ise-e** [comment]
방금 현재 상태를 반영하여 수정하였습니다
